package advent2025_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/willmadison/advent/advent2025"
)

func TestCountTachyonBeamSplits(t *testing.T) {
	given := strings.NewReader(`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`)

	expectedSplits := 21

	splits, err := advent2025.CountTachyonBeamSplits(given)

	assert.Nil(t, err)

	assert.Equal(t, expectedSplits, splits)
}

func TestCountQuantumTimelines(t *testing.T) {
	given := strings.NewReader(`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`)

	expectedTimelines := 40

	timelines, err := advent2025.CountQuantumTimelines(given)

	assert.Nil(t, err)

	assert.Equal(t, expectedTimelines, timelines)
}
